# Site settings
title: lamdeyton
header-img: img/home-bg.jpg
email: ldddeyton@gmail.com
description: "My Blog For Sharing with people around the world!"
baseurl: ""
url: "http://lamdeyton.github.io"
twitter_username: lamdeyton
github_username:  lamdeyton
facebook_username:  LamDeyton

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
